---
- include: common.yml

- name: Copy install script
  copy:
    src: install_swift.sh
    dest: /tmp/
    mode: "0755"

- name: Run install script
  shell:
    ./install_swift.sh
  args:
    chdir: /tmp
    executable: /bin/bash

- name: Allow public usage of /tmp
  file:
    name: /tmp
    mode: "0755"
    recurse: yes
